# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    - refs/tags/*
jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.302'
    - powershell: .\build.ps1
      displayName: 'Run build.ps1'
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.302'
    - script: |
        chmod +x ./build.sh
      displayName: 'Chmod build.sh'
    - script: |
        ./build.sh
      displayName: 'Run build.sh'